const data = {
  products: [
    {
      _id: 1,
      image: [
        "/images/luffyselfie.png",
        "/images/second.jpg",
        "/images/third.jpg",
        "/images/luffy.jpg",
        "/images/luffy.jpg",
      ],

      title: "One Piece Monkey D. Luffy",
      slug: "one-piece-monkey-d-luffy",
      item: "One Piece",
      category: "Collectible",
      price: 30000,
      saleprice: 25000,
      stocks: 5,
      properties: "Pre Order",
      description:
        "Pre-order deadline: August 24, 2024 ETA: Q4 2025. Natasha Romanoff a.k.a. Black Widow, first appeared in the 2010 film Iron Man 2, posing as a new assistant for Iron Man while working with S.H.I.E.L.D. She is a skilled spy, assassin, and combat expert one of the founding members of the Avengers team. Scarlett Johansson's portrayal of the character has been widely praised and the character has become a fan favorite in the Marvel universe. Sideshow and Hot Toys is delighted to introduce the Black Widow (Artisan Edition) Sixth Scale Collectible Figure depicting her debut appearance in Iron Man 2 movie. This exquisitely crafted Marvel action figure employs an innovative hair implantation technique using wool material, results in a head sculpt that beautifully replicates Black Widow’s refined facial features and her wavy, flowing amburn hair. The Black Widow Sixth Scale Figure includes a newly developed head sculpt with separate rolling eyeballs, a meticulously tailored jumpsuit, and an array of accessories that faithfully reproduce her tactical gear from the film. From the signature Black Widow's bite wristlets to her utility belt. The figure even includes a specially designed magnetic figure stand for display. A Special Edition available in selected markets with limited quantity 4,000 worldwide units will include Iron Man gauntlet and interchangeable hands as bonus accessory. Grasp the opportunity to elevate your Marvel collection! The Black Widow (Artisan Edition) (Special Edition) Sixth Scale Figure features: Authentic and detailed likeness of Scarlett Johansson as Black Widow in Iron Man 2 One (1) newly developed head sculpt with separate rolling eyeball system Movie-accurate facial expression and make-up Greatly detailed red amburn curly hair style using hair implantation (wool material) Body with over 28 points of articulations Approximately 28 cm tall Twelve (12) pieces of interchangeable hands including: One (1) pair of fists One (1) pair of relax hands One (1) pair of open hands One (1) pair of pistol holding hands One (1) pair of shuriken holding hands One (1) gesture left hand One (1) spray can holding right hand Each head sculpt is specially hand-painted Non-Special Edition without bonus accessory will be available in the limited quantity of 2,000 units in selected markets worldwide Costume: One (1) dark blue colored one-piece jumpsuit with belt One (1) pair of black-colored Black Widow’s bite One (1) greyish black colored belt with pouches and pistol holster One (1) pair of greyish black colored platform boots Weapons: Two (2) pistols Two (2) taser disks Two (2) activated taser disks One (1) rope Accessories: One (1) spray can Specially designed figure base with magnetic feature, movie logo and character nameplate",
    },
    {
      _id: 2,
      image: ["/images/mihawk.png"],
      title: "One Piece Dracule Mihawk",
      slug: "one-piece-dracule-mihawk",
      item: "One Piece",
      category: "Collectible",
      price: 50000,
      stocks: 1,
      properties: "Pre Order",
    },
    {
      _id: 3,
      image: ["/images/robin.png"],
      title: "One Piece Nico Robin",
      slug: "one-piece-nico-robin",
      item: "One Piece",
      category: "Collectible",
      saleprice: 1500,
      price: 3000,
      stocks: 1,
      properties: "Pre Order",
    },
    {
      _id: 4,
      image: ["/images/supermario.png"],
      title: "SuperMario Mario",
      slug: "supermario-mario",
      item: "Super Mario",
      category: "Collectible",
      price: 13000,
      stocks: 5,
      properties: "Pre Order",
    },
    {
      _id: 5,
      image: ["/images/kuzan.png"],
      title: "One Piece Aokiji Kuzan",
      slug: "one-piece-aokiji-kuzan",
      item: "One Piece",
      category: "Collectible",
      price: 2000,
      stocks: 2,
      properties: "Latest Product",
    },
    {
      _id: 6,
      image: ["/images/corazon.png"],
      title: "One Piece Don Quixote Rosinante",
      slug: "one-piece-don-quixote-rosinante",
      item: "DC",
      category: "Collectible",
      saleprice: 95000,
      price: 2000,
      stocks: 0,
      properties: "Latest Product",
    },
    {
      _id: 7,
      image: ["/images/luffyselfie.png"],
      title: "One Piece Monkey D. Luffy Gear 2",
      slug: "one-piece-monkey-d-luffy-gear-2",
      item: "One Piece",
      category: "Collectible",
      price: 50000,
      saleprice: 20000,
      onSale: "sale",
      stocks: 1,
      properties: "Latest Product",
    },
    {
      _id: 8,
      image: ["/images/luffy.jpg"],
      title: "One Piece Monkey D. Luffy Gear 3",
      slug: "one-piece-monkey-d-luffy-gear-3",
      item: "One Piece",
      category: "Collectible",
      price: 70000,
      saleprice: 20000,
      stocks: 1,
      properties: "Pre Order",
    },
    {
      // _id: 9,
      image: ["/images/luffy.jpg"],
      title: "One Piece Monkey D. Luffy Gear 4",
      slug: "one-piece-monkey-d-luffy-gear-4",
      item: "One Piece",
      category: "Collectible",
      price: 50000,
      saleprice: 20000,
      stocks: 1,
      properties: "Pre Order",
    },
    {
      // _id: 10,
      image: ["/images/luffy.jpg"],
      title: "One Piece Monkey D. Luffy Gear 5",
      slug: "one-piece-monkey-d-luffy-gear-2",
      item: "One Piece",
      category: "Collectible",
      price: 50000,
      saleprice: 20000,
      stocks: 1,
      properties: "Latest Product",
    },
    {
      // _id: 11,
      image: ["/images/luffy.jpg"],

      title: "One Piece Nami",
      slug: "one-piece-nami",
      item: "One Piece",
      category: "Collectible",
      price: 50000,
      saleprice: 20000,
      stocks: 1,
    },
    {
      // _id: 12,
      image: ["/images/luffy.jpg"],
      title: "One Piece Frankly",
      slug: "one-piece-frankly",
      item: "One Piece",
      category: "Collectible",
      price: 50000,
      saleprice: 20000,
      stocks: 1,
    },
    {
      // _id: 13,
      image: ["/images/luffy.jpg"],
      title: "One Piece Monkey D. Luffy Zombie",
      slug: "one-piece-monkey-d-luffy-zombie",
      item: "One Piece",
      category: "Collectible",
      price: 50000,
      stocks: 1,
    },
  ],
  apparelsProduct: [
    {
      // _id: 14,
      image: ["/images/cap-gray.png"],
      title: "Nintendo64 Cap Gray",
      slug: "nintendo64-cap-gray",
      item: "Cap",
      category: "Apparel",
      price: 75000,
      stocks: 2,
      addNew: "New Items",
    },
    {
      // _id: 15,
      image: ["/images/cap-supreme.png"],
      title: "Supreme Cap",
      slug: "supreme-cap",
      item: "Cap",
      category: "Apparel",
      price: 75000,
      stocks: 3,
      addNew: "New Items",
    },
    {
      // _id: 16,
      image: ["/images/nba-jacket.png"],
      title: "Nike Men’s WindBreaker",
      slug: "nike-men-windbreaker",
      item: "Jacket",
      category: "Apparel",
      price: 5000,
      stocks: 0,
      addNew: "New Items",
    },
    {
      // _id: 17,
      image: ["/images/longsleeve.png"],
      title: "Adidas Originals Mens Lifestyle Long Sleeve Top",
      slug: "adidas-originals-mens-lifestyle-long-sleeve-top",
      item: "Jacket",
      category: "Apparel",
      price: 5000,
      stocks: 4,
      addNew: "New Items",
    },
  ],
  banner: [
    {
      _id: 1,
      image: "/images/wallpaper.png",
      link: "/#",
      text: "hello",
    },
    {
      _id: 2,
      image: "/images/second.jpg",
      link: "/#",
      text: "hi",
    },
    { _id: 3, image: "/images/third.jpg", link: "/#" },
  ],
};

export default data;
