const data = {
  products: [
    {
      _id: 1,
      image: "/images/luffy.jpg",
      title: "One Piece asddasd sadDracule Mihawk",
      genre: "One Piece",
      oldPrice: "₱9,500.00",
      price: "₱7,500.00",
      link: "/#",
      aosDelay: "0",
    },
    {
      _id: 2,
      image: "/images/luffy.jpg",
      title: "One Piece Monkey D. Luffy",
      genre: "One Piece",
      price: "₱20,000.00",
      stocks: "Stocks: 1",
      link: "/#",
      aosDelay: "50",
    },
    {
      _id: 3,
      image: "/images/luffy.jpg",
      title: "One Piece Monkey D. Luffy",
      genre: "One Piece",
      oldPrice: "₱9,500.00",
      price: "₱20,000.00",
      stocks: "Stocks: 1",
      link: "/#",
      aosDelay: "100",
    },
    {
      _id: 4,
      image: "/images/luffy.jpg",
      title: "One Piece Monkey D. Luffy",
      genre: "One Piece",
      price: "₱20,000.00",
      stocks: "Stocks: 1",
      link: "/#",
      aosDelay: "150",
    },
    {
      _id: 5,
      image: "/images/luffy.jpg",
      title: "One Piece Monkey D. Luffy",
      genre: "One Piece",
      price: "₱20,000.00",
      stocks: "Stocks: 1",
      link: "/#",
      aosDelay: "100",
    },
    {
      _id: 6,
      image: "/images/luffy.jpg",
      title: "One Piece Monkey D. Luffy",
      genre: "One Piece",
      oldPrice: "₱9,500.00",
      price: "₱2,000.00",
      stocks: "Stocks: 1",
      link: "/#",
      aosDelay: "150",
    },
    {
      _id: 7,
      image: "/images/luffy.jpg",
      title: "One Piece Monkey D. Luffy",
      genre: "One Piece",
      price: "₱20,000.00",
      oldPrice: "₱50,000.00",
      onSale: "sale",
      stocks: "Stocks: 1",
      link: "/#",
    },
  ],
  banner: [
    {
      _id: 1,
      image: "/images/wallpaper.png",
      link: "/#",
      text: "hello",
    },
    {
      _id: 2,
      image: "/images/second.jpg",
      link: "/#",
      text: "hi",
    },
    { _id: 3, image: "/images/third.jpg", link: "/#" },
  ],
};

export default data;
